config/routes.rb
Store::Application.routes.draw do
  resources :categories

  get 'admin' => 'admin#index'
  get 'static_pages_about' => 'static_pages#about'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  match '/login' => "sessions#new", :as => "login"
  match '/logout' => "sessions#destroy", :as => "logout"
  match '/about' => "static_pages#about"
  match '/contact' => "static_pages#contact"
  resources :users
  resources :orders
  resources :line_items
  resources :carts
  resources :categories
  resources :static_pages

  get "store/index"

  resources :products do
    get :who_bought, on: :member
  end

  root to: 'store#index', as: 'store'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_product(product_id)
    current_item = line_items.find_by_product_id(product_id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product_id)
    end
    current_item
  end
  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

  def item_count
    line_items.to_a.sum { |item| item.quantity }

    # Paul's method to show quantity of basket items.
    end

end

app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  has_many :products
end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :order
  belongs_to :product
  belongs_to :cart
  attr_accessible :cart_id, :product_id

  def total_price
    product.price * quantity
  end
end

app/models/order.rb
class Order < ActiveRecord::Base
  PAYMENT_TYPES = [ "Cheque", "Credit card", "Purchase order" ]
  attr_accessible :address, :email, :name, :pay_type
  has_many :line_items, dependent: :destroy

  validates :name, :address, :email, presence: true
  validates :pay_type, inclusion: PAYMENT_TYPES
  def add_line_items_from_cart(cart)
    cart.line_items.each do |item|
      item.cart_id = nil
      line_items << item
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base

  has_many :line_items
  has_many :orders, through: :line_items
  belongs_to :category

  before_destroy :ensure_not_referenced_by_any_line_item

  attr_accessible :description, :image_url, :price, :title, :category_id

  validates :title, :description, :image_url, presence: true
  validates :price, numericality: {greater_than_or_equal_to: 0.01}
  validates :title, uniqueness: true
  validates :image_url, allow_blank: true, format: {
      with:    %r{\.(gif|jpg|png)\Z}i,
      message: 'must be a URL for GIF, JPG or PNG image.'
  }
  validates :title, length: {minimum: 10}

  def self.search(search_query)
    if search_query
      find(:all,:conditions => ['title LIKE ?', "%#{search_query}%"])
      # replace 'title' with relevant attributes
    else
      find(:all)
    end
  end
  private

  # ensure that there are no line items referencing this product
  def ensure_not_referenced_by_any_line_item
    if line_items.empty?
      return true
    else
      errors.add(:base, 'Line Items present')
      return false
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :name, :password, :password_confirmation, :admin
  validates :name, presence: true, uniqueness: true
  has_secure_password

  after_destroy :ensure_an_admin_remains

  private
  def ensure_an_admin_remains
    if User.count.zero?
      raise "Can't delete last user"
    end
  end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  def index
    @total_orders = Order.count
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  skip_before_filter :authorize, only: [:create, :update, :destroy]
  # GET /carts
  # GET /carts.json
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  # GET /carts/1
  # GET /carts/1.json
  def show
    begin
      @cart = Cart.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to store_url, notice: 'Invalid cart'
    else
      respond_to do |format|
        format.html # show.html.erb
        format.json { render json: @cart }
      end
    end
  end

  # GET /carts/new
  # GET /carts/new.json
  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  # GET /carts/1/edit
  def edit
    @cart = Cart.find(params[:id])
  end

  # POST /carts
  # POST /carts.json
  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /carts/1
  # PUT /carts/1.json
  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart, notice: 'Cart was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /carts/1
  # DELETE /carts/1.json
  def destroy
    @cart = current_cart
    @cart.destroy
    session[:cart_id] = nil

    respond_to do |format|
      format.html { redirect_to store_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/store_controller.rb
class StoreController < ApplicationController
  skip_before_filter :authorize, only: [:index,:show]
  def index
    @products = Product.all.sample(4)
    @cart = current_cart
  end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  def hidden_div_if(condition, attributes = {}, &block)
    if condition
      attributes["style"] = "display: none"
    end
    content_tag("div", attributes, &block)
  end
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/store_helper.rb
module StoreHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index.html.erb
<h1>Welcome</h1>

It's <%= Time.now %>
We have <%= pluralize(@total_orders, "order") %>.

app/views/layouts/application.html.erb
<!-- START:head -->
<!DOCTYPE html>
<html>
<head>
     <title>Fruit & Veg Online</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<!-- END:head -->
<body class="<%= controller.controller_name %>">
<div id=""
<div style="float:right; padding:20px 30px;">
  <% if session[:user_id] %>
      Hi <%= link_to current_user.name, current_user, :title => "click to view your account" %>
      <%= link_to "Sign out", logout_path %>
  <% else %>
      <%= link_to "Sign in", login_path %>  or
      <%= link_to "Create Account", new_user_path   %>
  <% end %>
</div>
<div style="float:right; clear:both; padding-right:50px;">
  <%= form_tag products_path, :method => 'get' do %>
      <p>
        <%= text_field_tag :search_query, params[:search_query] %>
        <%= submit_tag "Search", :name => nil %>
      </p>
  <% end %>
</div>



<div id="banner" style="clear:both;">
  <%= link_to image_tag("logo5.png", :width => 488, :height => 156), store_index_url %>

  <ul id="menu">
    <li><a href="/store/index">Home</a><li>
    <li><a href="/about">About Us</a></li>
    <li><a href="http://www..../news">Special Offers</a></li>
    <li><a href="http://www..../news">News</a></li>
    <li><a href="/contact">Contact Us</a></li>
  </ul>

</div>
<div id="columns">
  <div id="side">


    <h4>Start Shopping!</h4>
      <ul>
      <li><a href="/categories/1">Fruit</a>
      <li><a href="/categories/2">Vegetables</a>
      <li><a href="/products">All Products</a>
    </ul>

    <!-- START:hidden_div -->
    <% if @cart %>
        <%= hidden_div_if(@cart.line_items.empty?, id: 'cart') do %>
            <%= render @cart %>
        <% end %>
    <% end %>
    <!-- END:hidden_div -->


    <!-- START_HIGHLIGHT -->

    <% if session[:user_id] and current_user.admin %>
        <h3>Admin Area </h3>    <ul>
          <li><%= link_to 'Orders',   orders_path   %></li>
          <li><%= link_to 'Categories',   categories_path   %></li>
          <li><%= link_to 'Products', products_path %></li>
          <li><%= link_to 'Users',    users_path    %></li>
        </ul>
        <%= button_to 'Logout', logout_path, method: :delete   %>
    <% end %>
    <!-- END_HIGHLIGHT -->
  </div>
  <div id="main">
    <%= yield %>
  </div>
</div>
</body>
</html>